version: '3.7'
services:
    db:
        image: postgres:13.4
        restart: always
        user: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_DB: test
            POSTGRES_PASSWORD: ''
            # TODO: change this before deploying
            POSTGRES_HOST_AUTH_METHOD: 'trust'
        ports:
            - '5433:5432'

    migration:
        build:
          context: .
          target: backend
        volumes:
          - .:/app
        depends_on:
          - db
        command: npm run migrate

    backend:
        build:
          context: .
          target: backend
        volumes:
            - .:/app
        links:
            - 'db'
        depends_on:
            - db
            - migration
        ports:
            - '3001:3001'
            - '3000:3000'
        environment:
          DB_HOST: db
        command: npm run start
