version: '3.7'
services:
    frontend:
        build:
          context: .
          target: frontend
        ports:
            - "3001:3001"
        volumes:
            - ./src:/app/src
            - ./public:/app/public
            - ./scripts:/app/scripts
        command: npm run start
